### ISSUE TITLE
Add PHPStan 

### ISSUE THREAD

**Issue by marcinkrzeminski** [xfiveco/generator-chisel#535]
Add code quality inspections via PHPStan

- https://phpstan.org/
- https://github.com/szepeviktor/phpstan-wordpress

Example of `phpstan.neon`

```
parameters:
  level: 6
  scanDirectories:
    - wp/wp-content/plugins/
```
